language: php

sudo: false

matrix:
    fast_finish: true
    include:
        - php: 7.1
        - php: 7.2

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - travis_retry composer self-update
    - composer install

script: vendor/bin/phpunit
